program: tests/test_linear_probe_trainable_hp.py  # Specifies the script to run
method: grid  # Use the random search strategy
metric:
  name: val_accuracy  # The metric to optimize
  goal: maximize  # Aim to maximize the validation accuracy
parameters:
  learning_rate:
    values: [0.05, 0.1, 0.2, 0.3]
  n_estimators:
    values: [100, 250, 500, 750, 1000]  # Common sizes for the number of latent vectors
  max_depth:
    values: [6, 8, 10]  # Common dimensions for each latent vector
  models:
    values: ['UN,HB']
  dataset:
    values: ['pathmnist']