program: tests/test_linear_probe_trainable_hp.py  # Specifies the script to run
method: grid  # Use the random search strategy
metric:
  name: val_accuracy  # The metric to optimize
  goal: maximize  # Aim to maximize the validation accuracy
parameters:
  learning_rate:
    values: [0.1, 0.2, 0.3]
  n_estimators:
    values: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000]  
  models:
    values: ['CO,RD,CA']
  dataset:
    values: ['chestmnist']